### ISSUE TITLE
Properties parameter to the configure API has become required in 1.6.1

### ISSUE THREAD

**Issue by kcuzner** [microsoft/debugpy#975]
## Environment data

- debugpy version: 1.6.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows 10 / CentOS 7 (fails on both)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2 via pyenv
- Using VS Code or Visual Studio: No

## Actual behavior

I am doing the following in my module, which worked in 1.6.0:

```python
debugpy.configure(python=_path_to_any_working_python3())
debugpy.listen(5678)
```
Upon running my script, which has `debugpy.configure` executing as the module is importing, I get the following stack dump:

```
#                        File "<snip>", line 89, in <module>
#
#                          debugpy.configure(python=_path_to_any_working_python3())
#
#                        File "<snip>\lib\site-packages\debugpy\public_api.py", line 31, in wrapper
#
#                          return wrapped(*args, **kwargs)
#
#                      TypeError: configure() missing 1 required positional argument: 'properties'
```

It would appear that the `properties` argument to `configure` suddenly became required. Was this intentional? Or was I perhaps using it wrong in the first place?

## Expected  behavior

No errors

## Steps to reproduce:
1. Install debugpy 1.6.1
2. Use the configure function in the same manner as worked in 1.6.0
3. ...
4. Profit!

**Comment by fabioz** [comment]
This really seems like some unintended change in the `debugpy` api.

@int19h would you like to take a look at that or do you want me to check it?

@kcuzner the workaround until this is fixed is doing one of the calls below:

```
debugpy.configure({'python':_path_to_any_working_python3()})
debugpy.configure({}, python=_path_to_any_working_python3())
```

**Comment by int19h** [comment]
This is a regression from the refactoring that added type signatures. I'll address this ASAP. As it is a breaking API change, the fix warrants a point release.
