### ISSUE TITLE
AttributeError on Debug Run with PyTest

### ISSUE THREAD

**Issue by small-pants** [microsoft/debugpy#1951]
## Environment data

- debugpy version: 1.8.16
- OS and version: Ubuntu 20.04.6 LTS
- Python version: 3.12.3
- Using VS Code or Visual Studio: VS Code

## Actual behavior

```
collecting ... Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/__main__.py", line 229, in <module>
    __import__("debugpy")
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../debugpy/__init__.py", line 36, in <module>
    from debugpy.public_api import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../debugpy/public_api.py", line 25, in <module>
    @dataclasses.dataclass(frozen=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp/.pyenv/versions/3.12.3/envs/dev/lib/python3.12/site-packages/debugpy/adapter/../../dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
                           ^^^^^^^^^^^^^^^^
AttributeError: module 'typing' has no attribute '_ClassVar'. Did you mean: 'ClassVar'?
```

## Expected  behavior

PyTest collects test(s), macro in code waits for connection from VS Code, debugging proceeds.

## Steps to reproduce:
Use debugpy version 1.8.16 (downgrading to 1.8.15 fixed the problem), run a pytest for code that contains the debugpy code macro as I have below and wait a few seconds. The traceback will be reported and the `wait_for_client()` call will time out.
```
import debugpy
debugpy.listen(5679)
debugpy.wait_for_client()
```

**Comment by rchiodo** [comment]
Your 3.12 is rather old.  The version I'm using doesn't reference `typing._ClassVar` in dataclasses.py

Do you have some sample code that reproduces the problem? Is it just any pytest test?

**Comment by rchiodo** [comment]
I tried this and it worked with 1.8.16:

```
import pytest


@pytest.mark.parametrize("real_fixture", ["4", "5"])
def test_foo(real_fixture):
    import debugpy
    debugpy.listen(5679)
    debugpy.wait_for_client()
    assert real_fixture in ["1", "2", "3"]
```

Perhaps when you switched to 1.8.15, you used a different python?

**Comment by small-pants** [comment]
I'm locked inside a UV environment with that Python version. I'm fairly certain it's any test.
