### ISSUE TITLE
Crash on start when debug Python 3.14t.rc02

### ISSUE THREAD

**Issue by Honghe** [microsoft/debugpy#1953]
## Environment data

- debugpy version: 1.8.16
- OS and version: windows 11
- Python version:  conda-forge python 3.14.rc02 free-threaded
- Using VS Code or Visual Studio: vscode

## Actual behavior

vscode debug crash on start:

```
>  & 'c:\Users\x\miniforge3\envs\py314t\python.exe' 'c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\bundled\libs\debugpy\launcher' '63765' '--' 'E:\pythonprojects\uv_py314t\csp.py' 
Traceback (most recent call last):
  File "c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_sys_monitoring\_pydevd_sys_monitoring.py", line 876, in _unwind_event
    if not thread_info.trace or not thread_info.is_thread_alive():
  File "c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_sys_monitoring\_pydevd_sys_monitoring.py", line 270, in is_thread_alive
    return not self.thread._handle.is_done()
AttributeError: '_MainThread' object has no attribute '_handle'
```

## Expected  behavior

It can debug the following code.

## Steps to reproduce:
debug the following code:

```python
from concurrent import interpreters

interp = interpreters.create()

def run(q):
    print("before arg")
    print(q.get())

q = interpreters.create_queue()
t = interp.call_in_thread(run, q)
q.put("Hello from the main thread!")
t.join()
```

**Comment by rchiodo** [comment]
That version of the debugger extension is not using the debugpy 1.8.16. It's still on 1.8.13.

If you upgrade the ms-python.vsdebug extension to the insider's version, it should work with 3.14.

**Comment by Honghe** [comment]
> That version of the debugger extension is not using the debugpy 1.8.16. It's still on 1.8.13.
> 
> If you upgrade the ms-python.vsdebug extension to the insider's version, it should work with 3.14.

After upgrade ms-python.vsdebug to `2025.11.2025072901`， it still doesn't work.

```
>'c:\Users\x\miniforge3\envs\py314t\python.exe' 'c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.11.2025072901-win32-x64\bundled\libs\debugpy\launcher' '49673' '--' 'E:\pythonprojects\demo_python314\csp.py' 
Traceback (most recent call last):
  File "c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.11.2025072901-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_sys_monitoring\_pydevd_sys_monitoring.py", line 876, in _unwind_event
    if not thread_info.trace or not thread_info.is_thread_alive():
  File "c:\Users\x\.vscode\extensions\ms-python.debugpy-2025.11.2025072901-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_sys_monitoring\_pydevd_sys_monitoring.py", line 270, in is_thread_alive
    return not self.thread._handle.is_done()
AttributeError: '_MainThread' object has no attribute '_handle'
```

**Comment by rchiodo** [comment]
Oh it seems that's still on 1.8.13. Not sure when they're going to update. But that's the root cause of the bug.

**Comment by rchiodo** [comment]
There is a temporary workaround that you can use until the debugger extension updates. Put this in your launch.json:

```json
     "debugAdapterPath": "<path to debugpy>\\src\\debugpy\\adapter"
```

And pip install debugpy

**Comment by rchiodo** [comment]
When this commit ships:
https://github.com/microsoft/vscode-python-debugger/commit/b748cb8af2a1f78a9784f48d4b1f8ac66ce4f7f1

The extension should have the latest version.

**Comment by Honghe** [comment]
> There is a temporary workaround that you can use until the debugger extension updates. Put this in your launch.json:
> 
>      "debugAdapterPath": "<path to debugpy>\\src\\debugpy\\adapter"
> And pip install debugpy

It works, thanks.
How to inspec the running debugpy version of ms-python-debug extension except checking the static `debugpy_info.json` file?

**Comment by rchiodo** [comment]
You can print the debugpy version:

```
import debugpy
print(debugpy.__version__)
```

Either in code or in the debug console.
