### ISSUE TITLE
Build failure on Python 3.8/Win64 (while succesful for other Python versions and platforms)

### ISSUE THREAD

**Issue by SylvainCorlay** [microsoft/debugpy#229]
The conda-forge package for ptvsd fails to build on windows with Python 3.8. However, the package builds succesfully for other versions of Python, and other platforms.

```
 _pydevd_frame_eval\pydevd_frame_evaluator.c(7520): error C2037: left of 'eval_frame' specifies undefined struct/union '_is'
    _pydevd_frame_eval\pydevd_frame_evaluator.c(7619): error C2037: left of 'eval_frame' specifies undefined struct/union '_is'
```

A full build log is available in PR https://github.com/conda-forge/ptvsd-feedstock/pull/15.

If a ptvsd maintainer could chime into this issue with the feedstock, it would be fantastic! This is a significant blocker for the packaging of several other project

**Comment by int19h** [comment]
Judging by the build logs, this is for ptvsd 4.3.2. We don't intend to make any further changes to ptvsd - what was originally intended to be ptvsd 5.0 became debugpy, and all fixes and improvements are happening in that codebase. Dependencies should upgrade accordingly.

For debugpy, Python 3.8 support was tracked by https://github.com/microsoft/debugpy/issues/35, so this should be working there.

**Comment by SylvainCorlay** [comment]
I understand, although if you are aware of a workaround for those who still depend on this version of PTVSD, any guidance would be appreciated!

**Comment by SylvainCorlay** [comment]
I just realized I opened this on debugpy rather than ptvsd. Happy to close this and open in the other repository.

**Comment by int19h** [comment]
Let me move the issue directly so that we can preserve all the comments.
